# Database Configuration
spring.datasource.url=jdbc:postgresql://192.168.5.84:7432/bonsett
spring.datasource.username=settuser
spring.datasource.password=123123

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false