spring.application.name=Invoicing System

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=10

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Keycloak Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://172.29.11.201:8086/realms/Invoicing%20System
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://172.29.11.201:8086/realms/Invoicing%20System/protocol/openid-connect/certs

cors.allowed.origins=*
server.port=8443