spring.application.name=Invoicing System

# Database Configuration
spring.datasource.url=jdbc:postgresql://172.29.11.110:5433/bonsett
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=10

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:defaultSecretKey}
jwt.expiration=1800000
cors.allowed.origins=*
server.port=8081